// ═══════════════════════════════════════════════════════════════════
// tb_lenet5_real — full Lenet5v3 with REAL weights from fold_params
//
//   lenet5v3_top (APB+AHB) + AHB memory slave + APB master + golden ref
//
//   5-layer chain: conv1(1→8ch,28×28,pad=2,pool) → conv2(8→16ch,14×14,pad=0,pool)
//              → fc1_p1(10ic,keep_accum) → fc1_p2(6ic→64ch)
//              → fc2(64→10ch)
//   Weights/requant loaded from $readmemh hex files generated by
//   preprocess_weights.py from fold_params.
//   Input: MNIST test[0] (label=7), golden from int8_hw_lenet5v3 method D.
// ═══════════════════════════════════════════════════════════════════
`default_nettype none
`timescale 1ns / 100ps

import wrapper_pkg::*;
import core_pkg::*;

module tb_lenet5_real;

    // ── Clocks & Reset ──
    logic        clk, rst_n;

    // ── APB ──
    logic        PSEL, PENABLE, PWRITE;
    logic [11:0] PADDR;
    logic [31:0] PWDATA, PRDATA;

    // ── AHB ──
    logic [31:0] HADDRM;
    logic  [1:0] HTRANSM;
    logic        HWRITEM;
    logic  [2:0] HSIZEM, HBURSTM;
    logic [31:0] HWDATAM, HRDATAM;
    logic        HREADYM;
    logic        HRESPM;
    logic        HMASTLOCKM;

    integer errors = 0;
    logic [31:0] rd;
    logic        sim_done = 1'b0;

    // ═══════════════════════════════════════════════════════════════
    // DUT
    // ═══════════════════════════════════════════════════════════════
    lenet5v3_top u_top (
        .PCLK(clk), .PRESETn(rst_n),
        .PSEL(PSEL), .PENABLE(PENABLE), .PWRITE(PWRITE),
        .PADDR(PADDR), .PWDATA(PWDATA), .PRDATA(PRDATA), .PREADY(),
        .HCLK(clk), .HRESETn(rst_n),
        .HADDRM(HADDRM), .HTRANSM(HTRANSM), .HWRITEM(HWRITEM),
        .HSIZEM(HSIZEM), .HBURSTM(HBURSTM), .HWDATAM(HWDATAM),
        .HRDATAM(HRDATAM), .HREADYM(HREADYM), .HRESPM(HRESPM),
        .HMASTLOCKM(HMASTLOCKM)
    );

    // ═══════════════════════════════════════════════════════════════
    // Clock & Reset
    // ═══════════════════════════════════════════════════════════════
    initial clk = 0; always #2.5 clk = ~clk;
    initial begin
        $dumpfile("tb_lenet5_real.vcd");
        $dumpvars(0, tb_lenet5_real);
    end

    // ═══════════════════════════════════════════════════════════════
    // AHB Memory Slave (64KB window)
    // ═══════════════════════════════════════════════════════════════
    logic [31:0] mem [0:16383];
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) HRDATAM <= 32'd0;
        else if (HREADYM && (HTRANSM == HTRANS_NONSEQ || HTRANSM == HTRANS_SEQ)) begin
            if (HWRITEM) mem[HADDRM[15:2]] <= HWDATAM;
            HRDATAM <= mem[HADDRM[15:2]];
        end
    end

    // ═══════════════════════════════════════════════════════════════
    // APB tasks
    // ═══════════════════════════════════════════════════════════════
    task apb_write(input [11:0] addr, input [31:0] data);
        @(posedge clk); PSEL=1; PENABLE=0; PWRITE=1; PADDR=addr; PWDATA=data;
        @(posedge clk); PENABLE=1;
        @(posedge clk); PSEL=0; PENABLE=0;
    endtask
    task apb_read(input [11:0] addr, output [31:0] data);
        @(posedge clk); PSEL=1; PENABLE=0; PWRITE=0; PADDR=addr;
        @(posedge clk); PENABLE=1;
        @(posedge clk); data = PRDATA; PSEL=0; PENABLE=0;
    endtask
    task tick(input integer n); for (int i=0;i<n;i++) @(posedge clk); endtask

    // ═══════════════════════════════════════════════════════════════
    // Descriptor builder — matches shadow_register bit-slice layout
    // ═══════════════════════════════════════════════════════════════
    function [13:0] widx(input [31:0] ba); widx = ba[15:2]; endfunction

    task put_desc(
        input [31:0] base,
        input  [7:0] in_ch,  input  [7:0] out_ch,
        input  [7:0] in_w,   input  [7:0] in_h,
        input  [3:0] kw,     input  [3:0] kh,
        input  [3:0] sw,     input  [3:0] sh,
        input  [3:0] pw,     input  [3:0] ph,
        input  [7:0] zp_y,   input        pool_bypass,
        input  [7:0] out_w,  input  [7:0] out_h,
        input  [8:0] im_rd,  input  [8:0] im_wr,  input [15:0] im_tw,
        input  [7:0] im_row_stride, input [9:0] im_ch_stride,
        input  [7:0] out_row_stride, input [9:0] out_ch_stride,
        input  [7:0] wt_ch_stride, input [7:0] wt_row_stride, input [9:0] wt_ocg_stride,
        input        mode, input ct_mode,
        input [31:0] wt_bytes, input [31:0] rq_bytes,
        input [31:0] wt_ptr,   input [31:0] rq_ptr,
        input [31:0] feat_ptr, input [31:0] feat_bytes,
        input [31:0] res_ptr,  input [31:0] next_desc, input is_last,
        input        keep_accum, input disable_flush
    );
        integer b;
        begin
            for (b=0;b<16;b++) mem[widx(base)+b]=32'd0;
            mem[widx(base)+0] = {in_h, in_w, out_ch, in_ch};
            mem[widx(base)+1] = {sh, sw, kh, kw, out_h, out_w};
            mem[widx(base)+2] = {im_tw, zp_y, ph, pw};
            mem[widx(base)+3] = {5'd0, im_rd, im_ch_stride, im_row_stride};
            mem[widx(base)+4] = {5'd0, im_wr, out_ch_stride, out_row_stride};
            mem[widx(base)+5] = {1'd0, ct_mode, disable_flush, keep_accum, pool_bypass, mode,
                                 wt_ocg_stride, wt_row_stride, wt_ch_stride};
            mem[widx(base)+6]  = wt_bytes;
            mem[widx(base)+7]  = rq_bytes;
            mem[widx(base)+8]  = wt_ptr;
            mem[widx(base)+9]  = rq_ptr;
            mem[widx(base)+10] = feat_ptr;
            mem[widx(base)+11] = res_ptr;
            mem[widx(base)+12] = feat_bytes;
            mem[widx(base)+13] = next_desc;
            mem[widx(base)+14] = {31'd0, is_last};
        end
    endtask

    // ═══════════════════════════════════════════════════════════════
    // Golden reference — precomputed from int8_hw_lenet5v3 method D
    //
    //   MNIST test[0] (label=7), model forward_raw output:
    //   Raw uint8 logits (10ch): [83, 86, 93, 98, 90, 92, 36, 153, 83, 109]
    //   Packed as CT_GEARBOX 64-bit words (little-endian bytes):
    //     word[0] = 0x625D5653 (ch0=83,ch1=86,ch2=93,ch3=98)
    //     word[1] = 0x99245C5A (ch4=90,ch5=92,ch6=36,ch7=153)
    //     word[2] = 0x00006D53 (ch8=83,ch9=109, pad=0, pad=0)
    //   Dequantized: argmax = 7 (correct!)
    // ═══════════════════════════════════════════════════════════════
    localparam GOLDEN_W0 = 32'h625D5653;
    localparam GOLDEN_W1 = 32'h99245C5A;
    localparam GOLDEN_W2 = 32'h00006D53;

    // ═══════════════════════════════════════════════════════════════
    // Memory map — verified no overlaps
    //
    //   conv1:   5 wt rows (80 words),     2 rq entries (18 words)
    //   conv2:  80 wt rows (1280 words),   4 rq entries (36 words)
    //   fc1_p1: 250 wt rows (4000 words), 16 rq entries (144 words)
    //   fc1_p2: 150 wt rows (2400 words), 16 rq entries (144 words)
    //   fc2:    64 wt rows (1024 words),   3 rq entries (27 words)
    // ═══════════════════════════════════════════════════════════════
    localparam DESC0      = 32'h0100;
    localparam DESC1      = 32'h0200;
    localparam DESC_FC_P1 = 32'h0300;
    localparam DESC_FC_P2 = 32'h0380;
    localparam DESC_FC2   = 32'h0400;
    localparam FEAT       = 32'h0800;   // 224 words (ends 0x0B80)
    localparam WT0        = 32'h0C00;   //  80 words (ends 0x0D40)
    localparam RQ0        = 32'h0E00;   //  18 words (ends 0x0E48)
    localparam WT1        = 32'h1000;   // 1280 words (ends 0x2400)
    localparam RQ1        = 32'h2400;   //  36 words (ends 0x2490)
    localparam WT_FC_P1   = 32'h2800;   // 4000 words (ends 0x6680)
    localparam RQ_FC_P1   = 32'h6700;   // 144 words (ends 0x6940)
    localparam WT_FC_P2   = 32'h6A00;   // 2400 words (ends 0x8F80)
    localparam RQ_FC_P2   = 32'h9000;   // 144 words (ends 0x9240)
    localparam WT_FC2     = 32'h9300;   // 1024 words (ends 0xA300)
    localparam RQ_FC2     = 32'hA400;   //  27 words (ends 0xA46C)
    localparam RES        = 32'hB000;

    // Hex file paths
    localparam string HEX_DIR = "E:/Documents_E/vscode/lenet5/scripts/build/";

    integer i, k;

    // ═══════════════════════════════════════════════════════════════
    // Main
    // ═══════════════════════════════════════════════════════════════
    initial begin
        PSEL=0; PENABLE=0; PWRITE=0; PADDR=0; PWDATA=0;
        rst_n=0; HREADYM=1; HRESPM=1'b0;
        for (i=0;i<16384;i++) mem[i]=32'd0;
        tick(4); rst_n=1; tick(2);

        // ── Load weight / requant / feature data from hex files ──
        $display("[T] Loading real weights/requant/feature from per-layer hex files...");
        $readmemh({HEX_DIR, "wt_conv1.hex"},   mem, widx(WT0));
        $readmemh({HEX_DIR, "wt_conv2.hex"},   mem, widx(WT1));
        $readmemh({HEX_DIR, "wt_fc1_p1.hex"},  mem, widx(WT_FC_P1));
        $readmemh({HEX_DIR, "wt_fc1_p2.hex"},  mem, widx(WT_FC_P2));
        $readmemh({HEX_DIR, "wt_fc2.hex"},     mem, widx(WT_FC2));
        $readmemh({HEX_DIR, "rq_conv1.hex"},   mem, widx(RQ0));
        $readmemh({HEX_DIR, "rq_conv2.hex"},   mem, widx(RQ1));
        $readmemh({HEX_DIR, "rq_fc1_p1.hex"},  mem, widx(RQ_FC_P1));
        $readmemh({HEX_DIR, "rq_fc1_p2.hex"},  mem, widx(RQ_FC_P2));
        $readmemh({HEX_DIR, "rq_fc2.hex"},     mem, widx(RQ_FC2));
        $readmemh({HEX_DIR, "feature.hex"},    mem, widx(FEAT));
        $display("  All hex files loaded.");

        // Spot-check: first conv1 weight byte (oc=0, kx=0)
        $display("  Spot-check conv1 wt[7:0] (oc0,kx0) = 0x%02h", mem[widx(WT0)][7:0]);
        $display("  Spot-check feature word[0] = 0x%08h", mem[widx(FEAT)]);

        // ═══════════════════════════════════════════════════════════
        // Build descriptors — 5-layer chain with real parameters
        // ═══════════════════════════════════════════════════════════

        // ── Layer 0: Conv1 (1→8ch, 28×28, 5×5, pad=2, pool 2×2) ──
        put_desc(
            DESC0,
            8'd1, 8'd8,                              // in_ch=1, out_ch=8
            8'd28, 8'd28,                            // in_w=28, in_h=28
            4'd5, 4'd5, 4'd1, 4'd1, 4'd2, 4'd2,      // kw=5, kh=5, sw=1, sh=1, pw=2, ph=2
            8'd0, 1'b0,                              // zp_y=0, pool_bypass=0
            8'd28, 8'd28,                            // out_w=28, out_h=28
            9'd0, 9'd112, 16'd224,                   // im_rd=0, im_wr=112, im_tw=224
            8'd4, 10'd112,                           // im_row_stride=4, im_ch_stride=112
            8'd2, 10'd28,                            // out_row_stride=2, out_ch_stride=28
            8'd5, 8'd1, 10'd5,                       // wt_ch_stride=5, wt_row_stride=1, wt_ocg_stride=5
            MODE_8x8, CT_SPATIAL,
            32'd320, 32'd72,                         // wt_bytes=320 (5 rows), rq_bytes=72 (2 entries)
            WT0, RQ0,
            FEAT, 32'd896,                           // feat_ptr, feat_bytes=896
            32'd0, DESC1, 1'b0,                      // res_ptr=0, next=DESC1
            1'b0, 1'b0
        );

        // ── Layer 1: Conv2 (8→16ch, 14×14, 5×5, pad=0, pool 2×2) ──
        put_desc(
            DESC1,
            8'd8, 8'd16,                             // in_ch=8, out_ch=16
            8'd14, 8'd14,                            // in_w=14, in_h=14
            4'd5, 4'd5, 4'd1, 4'd1, 4'd0, 4'd0,      // kw=5, kh=5, sw=1, sh=1, pw=0, ph=0
            8'd0, 1'b0,                              // zp_y=0, pool_bypass=0
            8'd10, 8'd10,                            // out_w=10, out_h=10
            9'd112, 9'd336, 16'd80,                  // im_rd=112, im_wr=336, im_tw=80
            8'd2, 10'd28,                            // im_row_stride=2, im_ch_stride=28
            8'd1, 10'd5,                             // out_row_stride=1, out_ch_stride=5
            8'd5, 8'd1, 10'd40,                      // wt_ch_stride=5, wt_row_stride=1, wt_ocg_stride=40
            MODE_8x8, CT_SPATIAL,
            32'd5120, 32'd144,                       // wt_bytes=5120, rq_bytes=144
            WT1, RQ1,
            32'd0, 32'd0,                            // no feature fetch (IM already loaded)
            RES, DESC_FC_P1, 1'b0,                   // res_ptr=RES, next=FC_P1
            1'b0, 1'b0
        );

        // ── Layer 2: FC1 Part1 (ic=0..9, keep_accum=1, disable_flush=1) ──
        put_desc(
            DESC_FC_P1,
            8'd10, 8'd64,                            // in_ch=10, out_ch=64
            8'd5, 8'd5,                              // in_w=5, in_h=5
            4'd5, 4'd5, 4'd1, 4'd1, 4'd0, 4'd0,      // kw=5, kh=5, stride=1, pad=0
            8'd0, 1'b1,                              // zp_y=0, pool_bypass=1
            8'd1, 8'd1,                              // out_w=1, out_h=1
            9'd336, 9'd0, 16'd0,                     // im_rd=336, im_wr=0, im_tw=0 (no writeback)
            8'd1, 10'd5,                             // im_row_stride=1, im_ch_stride=5
            8'd1, 10'd1,                             // out_row_stride=1, out_ch_stride=1
            8'd25, 8'd5, 10'd1,                      // wt_ch_stride=25, wt_row_stride=5, wt_ocg_stride=1
            MODE_1x64, CT_GEARBOX,
            32'd16000, 32'd576,                      // wt_bytes=16000 (250 rows), rq_bytes=576 (16 entries)
            WT_FC_P1, RQ_FC_P1,
            32'd0, 32'd0,                            // no feature fetch
            32'd0, DESC_FC_P2, 1'b0,                 // res_ptr=0, next=FC_P2
            1'b1, 1'b1                               // keep_accum=1, disable_flush=1
        );

        // ── Layer 3: FC1 Part2 (ic=10..15, final accumulation + flush) ──
        put_desc(
            DESC_FC_P2,
            8'd6, 8'd64,                             // in_ch=6, out_ch=64
            8'd5, 8'd5,                              // in_w=5, in_h=5
            4'd5, 4'd5, 4'd1, 4'd1, 4'd0, 4'd0,
            8'd0, 1'b1,                              // zp_y=0, pool_bypass=1
            8'd1, 8'd1,                              // out_w=1, out_h=1
            9'd386, 9'd0, 16'd8,                     // im_rd=336+50=386, im_tw=8 (64ch/8)
            8'd1, 10'd5,                             // im_row_stride=1, im_ch_stride=5
            8'd1, 10'd1,                             // out_row_stride=1, out_ch_stride=1
            8'd25, 8'd5, 10'd1,                      // wt_ch_stride=25, wt_row_stride=5, wt_ocg_stride=1
            MODE_1x64, CT_GEARBOX,
            32'd9600, 32'd576,                       // wt_bytes=9600 (150 rows), rq_bytes=576 (16 entries)
            WT_FC_P2, RQ_FC_P2,
            32'd0, 32'd0,                            // no feature fetch
            32'd0, DESC_FC2, 1'b0,                   // res_ptr=0, next=FC2
            1'b0, 1'b0                               // keep_accum=0, disable_flush=0
        );

        // ── Layer 4: FC2 (64→10ch, 1×1, pad=0, final output) ──
        put_desc(
            DESC_FC2,
            8'd64, 8'd10,                            // in_ch=64, out_ch=10
            8'd1, 8'd1,                              // in_w=1, in_h=1
            4'd1, 4'd1, 4'd1, 4'd1, 4'd0, 4'd0,      // kw=1, kh=1, stride=1, pad=0
            8'd95, 1'b1,                              // zp_y=95 (real!), pool_bypass=1
            8'd1, 8'd1,                              // out_w=1, out_h=1
            9'd200, 9'd0, 16'd2,                     // im_rd=200, im_tw=2 (10ch/8 ceil)
            8'd1, 10'd1,                             // im_row_stride=1, im_ch_stride=1
            8'd1, 10'd1,                             // out_row_stride=1, out_ch_stride=1
            8'd1, 8'd1, 10'd1,                       // wt_ch_stride=1, wt_row_stride=1, wt_ocg_stride=1
            MODE_1x64, CT_GEARBOX,
            32'd4096, 32'd108,                       // wt_bytes=4096 (64 rows), rq_bytes=108 (3 entries)
            WT_FC2, RQ_FC2,
            32'd0, 32'd0,                            // no feature fetch
            RES, 32'd0, 1'b1,                        // res_ptr=RES, is_last=1
            1'b0, 1'b0
        );

        // ═══════════════════════════════════════════════════════════
        // Per-layer CT write probe + monitors
        // ═══════════════════════════════════════════════════════════
        fork
            // bank_toggle edge detect
            begin : bt_monitor
                automatic logic bt_prev = 1'b0;
                while (!sim_done) begin
                    @(posedge clk);
                    if (u_top.u_wrapper.bank_toggle != bt_prev) begin
                        $display("  [BANK_TOGGLE] %b→%b at t=%0t", bt_prev,
                                 u_top.u_wrapper.bank_toggle, $time);
                        bt_prev = u_top.u_wrapper.bank_toggle;
                    end
                end
            end

            // cfg_valid probe — track active layer
            begin : cfg_probe
                automatic integer cfg_cnt = 0;
                while (!sim_done) begin
                    @(posedge clk);
                    if (u_top.u_wrapper.cfg_valid) begin
                        cfg_cnt++;
                        $display("[CFG#%0d] t=%0t pool_bypass=%b mode=%b ct=%b in=%0dx%0dx%0d out=%0dx%0dx%0d k=%0dx%0d p=(%0d,%0d) s=(%0d,%0d) zp_y=%0d",
                                 cfg_cnt, $time,
                                 u_top.u_wrapper.cfg_core.pool_bypass,
                                 u_top.u_wrapper.cfg_core.mode,
                                 u_top.u_wrapper.cfg_core.ct_mode,
                                 u_top.u_wrapper.cfg_core.in_w,
                                 u_top.u_wrapper.cfg_core.in_h,
                                 u_top.u_wrapper.cfg_core.in_ch,
                                 u_top.u_wrapper.cfg_core.out_w,
                                 u_top.u_wrapper.cfg_core.out_h,
                                 u_top.u_wrapper.cfg_core.out_ch,
                                 u_top.u_wrapper.cfg_core.kernel_w,
                                 u_top.u_wrapper.cfg_core.kernel_h,
                                 u_top.u_wrapper.cfg_core.pad_w,
                                 u_top.u_wrapper.cfg_core.pad_h,
                                 u_top.u_wrapper.cfg_core.stride_w,
                                 u_top.u_wrapper.cfg_core.stride_h,
                                 u_top.u_wrapper.cfg_core.zp_y);
                        $display("  im_rd=%0d im_wr=%0d im_tw=%0d keep_accum=%b dis_flush=%b",
                                 u_top.u_wrapper.cfg_core.im_read_base,
                                 u_top.u_wrapper.cfg_core.im_write_base,
                                 u_top.u_wrapper.cfg_core.im_total_writes,
                                 u_top.u_wrapper.cfg_core.keep_accum,
                                 u_top.u_wrapper.cfg_core.disable_flush);
                    end
                end
            end

            // ── IM external write probe (feature loading) ──
            begin : im_ext_probe
                automatic integer im_ext_cnt = 0;
                while (!sim_done) begin
                    @(posedge clk);
                    if (u_top.im_ext_cs && u_top.im_ext_wr) begin
                        if (im_ext_cnt < 8)
                            $display("[IM_EXT_WR#%0d] addr=%0d data=0x%016h",
                                     im_ext_cnt, u_top.im_ext_addr,
                                     u_top.im_ext_wdata);
                        im_ext_cnt++;
                    end
                end
                $display("[IM_EXT] Total IM external writes: %0d (expect 112 for FETCH)", im_ext_cnt);
            end

            // ── Weight gearbox write probe ──
            begin : wt_gb_probe
                automatic integer wt_gb_cnt = 0;
                while (!sim_done) begin
                    @(posedge clk);
                    if (u_top.u_wrapper.wt_gb.wr_en) begin
                        if (wt_gb_cnt < 4)
                            $display("[WT_GB_WR#%0d] bank_sel=%b data=0x%08h",
                                     wt_gb_cnt, u_top.u_wrapper.wt_gb.bank_sel,
                                     u_top.u_wrapper.wt_gb.wdata);
                        wt_gb_cnt++;
                    end
                end
                $display("[WT_GB] Total weight gearbox writes: %0d", wt_gb_cnt);
            end

            // ── Per-layer CT write probe ──
            begin : ct_layer_probe
                automatic integer ct_layer      = 0;  // active layer index
                automatic integer ct_layer_cnt  = 0;  // CT writes in current layer
                automatic integer prev_cfg_cnt  = 0;
                while (!sim_done) begin
                    @(posedge clk);
                    // Track cfg_valid to know which layer is active
                    if (u_top.u_wrapper.cfg_valid) begin
                        ct_layer++;
                        ct_layer_cnt = 0;
                    end
                    // Capture CT writes
                    if (u_top.u_core.u_ct.im_wr_en) begin
                        if (ct_layer_cnt < 4 || ct_layer_cnt >= ct_layer_cnt + 1) begin
                            $display("[CT_L%0d#%0d] addr=%0d data=0x%016h",
                                     ct_layer, ct_layer_cnt,
                                     u_top.u_core.u_ct.im_wr_addr,
                                     u_top.u_core.u_ct.im_wr_data);
                        end
                        ct_layer_cnt++;
                    end
                end
                $display("[CT_PROBE] Done.");
            end
        join_none

        // ═══════════════════════════════════════════════════════════
        // APB: configure + start
        // ═══════════════════════════════════════════════════════════
        $display("[APB] Write DESC_HEAD_PTR=0x%08h", DESC0);
        apb_write({4'h0, APB_DESC_HEAD_PTR}, DESC0);
        apb_read({4'h0, APB_DESC_HEAD_PTR}, rd);
        if (rd !== DESC0) begin $display("FAIL: DESC_HEAD_PTR readback"); errors++; end

        $display("[APB] Write CTRL.start=1");
        apb_write({4'h0, APB_CTRL}, 32'd1);
        tick(5);

        // ═══════════════════════════════════════════════════════════
        // FSM Monitor + inference_done poll
        // ═══════════════════════════════════════════════════════════
        $display("[T] Monitoring FSM, waiting for inference_done...");
        $display("    Chain: DESC0→DESC1→FC_P1→FC_P2→FC2→end");

        i = 0;
        k = 0;  // AHB write counter
        begin
            automatic logic [1:0] prev_dma_fsm = 2'd0;
            automatic logic [1:0] dma_fsm;
            automatic logic       inf_done = 1'b0;
            while (!inf_done && i < 5000000) begin
                @(posedge clk); i++;
                if (HWRITEM && HREADYM && HTRANSM[1]) k++;

                if (i % 100 == 0) begin
                    apb_read({4'h0, APB_DEBUG_STATE}, rd);
                    dma_fsm = rd[1:0];
                    if (dma_fsm != prev_dma_fsm) begin
                        $display("  t=%0t: dma_fsm %0d→%0d (0=IDLE 1=PREFILL 2=PREFETCH 3=TAIL), core_busy=%b, toggle=%b",
                                 $time, prev_dma_fsm, dma_fsm, rd[9], rd[8]);
                        prev_dma_fsm = dma_fsm;
                    end
                    apb_read({4'h0, APB_INT_STATUS}, rd);
                    inf_done = rd[0];
                    if (inf_done) begin
                        sim_done = 1'b1;
                        tick(5);
                        $display("  t=%0t: inference_done=1, AHB writes=%0d", $time, k);
                    end
                end
            end
            if (!inf_done) begin $display("FAIL: timeout"); errors++; $finish; end
        end

        // ═══════════════════════════════════════════════════════════
        // Verify FC2 output at RES against golden
        // ═══════════════════════════════════════════════════════════
        $display("[CHK] Verifying FC2 output at RES=0x%08h", RES);
        $display("      Golden (PyTorch method D):");
        $display("        word[0]=0x%08h  word[1]=0x%08h  word[2]=0x%08h",
                 GOLDEN_W0, GOLDEN_W1, GOLDEN_W2);

        // Check for X
        k = 0;
        for (i=0; i<3; i++) begin
            automatic logic [31:0] got = mem[widx(RES)+i];
            if ($isunknown(got)) begin
                $display("  FAIL result[%0d]: X detected!", i);
                k++;
            end
        end

        // Golden comparison
        if (mem[widx(RES)+0] !== GOLDEN_W0) begin
            $display("  FAIL word[0]: got 0x%08h, expected 0x%08h",
                     mem[widx(RES)+0], GOLDEN_W0);
            k++;
        end else $display("  word[0] = 0x%08h ✓", mem[widx(RES)+0]);

        if (mem[widx(RES)+1] !== GOLDEN_W1) begin
            $display("  FAIL word[1]: got 0x%08h, expected 0x%08h",
                     mem[widx(RES)+1], GOLDEN_W1);
            k++;
        end else $display("  word[1] = 0x%08h ✓", mem[widx(RES)+1]);

        if (mem[widx(RES)+2] !== GOLDEN_W2) begin
            $display("  FAIL word[2]: got 0x%08h, expected 0x%08h",
                     mem[widx(RES)+2], GOLDEN_W2);
            k++;
        end else $display("  word[2] = 0x%08h ✓", mem[widx(RES)+2]);

        errors += k;
        $display("[CHK] Total WRITEBACK AHB writes: %0d", k);

        // Show raw output channels
        $display("[T] FC2 raw output (10 channels):");
        $display("    ch0=%0d ch1=%0d ch2=%0d ch3=%0d",
                 mem[widx(RES)+0][7:0], mem[widx(RES)+0][15:8],
                 mem[widx(RES)+0][23:16], mem[widx(RES)+0][31:24]);
        $display("    ch4=%0d ch5=%0d ch6=%0d ch7=%0d",
                 mem[widx(RES)+1][7:0], mem[widx(RES)+1][15:8],
                 mem[widx(RES)+1][23:16], mem[widx(RES)+1][31:24]);
        $display("    ch8=%0d ch9=%0d",
                 mem[widx(RES)+2][7:0], mem[widx(RES)+2][15:8]);

        if (errors==0) $display("\n==== TB_LENET5_REAL: ALL CHECKS PASSED ====");
        else           $display("\n==== %0d ERRORS ====", errors);
        $finish;
    end

    initial begin #50000000; $display("GLOBAL TIMEOUT"); errors++; $finish; end
endmodule

`default_nettype wire
